Update deploy-api-service-v2.yml

diff --git a/.github/workflows/deploy-api-service-v2.yml b/.github/workflows/deploy-api-service-v2.yml
--- a/.github/workflows/deploy-api-service-v2.yml
+++ b/.github/workflows/deploy-api-service-v2.yml
@@ -140,25 +140,25 @@ jobs:
           # echo "🔍 Health check:"
           # curl -v http://localhost:${{ vars. API_SERVICE_PORT }}/health || true
 
-      # - name: Healthcheck
-      #   run: |
-      #     HEALTHCHECK_URL="http://localhost:${{ vars.API_SERVICE_PORT}}/api-service/${{ vars.DOMAIN }}/${{vars.VERSION}}/health"
-      #     echo "Checking $HEALTHCHECK_URL ..."
-      #     for i in {1..10}; do
-      #       if curl -sSf "$HEALTHCHECK_URL" > /dev/null; then
-      #         echo "✅ Container is healthy"
-      #         exit 0
-      #       fi
-      #       echo "Waiting... ($i)"
-      #       sleep 2
-      #     done
-      #     echo "❌ Healthcheck failed!"
-      #     docker logs api-test
-      #     exit 1
+      - name: Healthcheck
+        run: |
+          HEALTHCHECK_URL="http://localhost:${{ vars.API_SERVICE_PORT}}/api-service/${{ vars.DOMAIN }}/${{vars.VERSION}}/health"
+          echo "Checking $HEALTHCHECK_URL ..."
+          for i in {1..10}; do
+            if curl -sSf "$HEALTHCHECK_URL" > /dev/null; then
+              echo "✅ Container is healthy"
+              exit 0
+            fi
+            echo "Waiting... ($i)"
+            sleep 2
+          done
+          echo "❌ Healthcheck failed!"
+          docker logs api-test
+          exit 1
 
-      # - name: Stop test container
-      #   if: always()
-      #   run: docker stop api-test || true
+      - name: Stop test container
+        if: always()
+        run: docker stop api-test || true
 
       - name: Tag & Push Images
         run: |
@@ -170,57 +170,57 @@ jobs:
           docker push $IMAGE_NAME:latest
           docker push $IMAGE_NAME:stable
 
-  deploy:
-    needs: build-and-verify
-    runs-on: ubuntu-latest
-    environment: ${{ github.ref_name }}  # environment exactly matches branch name
-    steps:
-      - name: Detect build type
-        run: |
-          if [[ "${GITHUB_REF_NAME}" == draft* ]]; then
-            echo "BUILD_TYPE=draft" >> $GITHUB_ENV
-          elif [[ "${GITHUB_REF_NAME}" == release* ]]; then
-            echo "BUILD_TYPE=release" >> $GITHUB_ENV
-          else
-            echo "BUILD_TYPE=default" >> $GITHUB_ENV
-          fi
+  # deploy:
+  #   needs: build-and-verify
+  #   runs-on: ubuntu-latest
+  #   environment: ${{ github.ref_name }}  # environment exactly matches branch name
+  #   steps:
+  #     - name: Detect build type
+  #       run: |
+  #         if [[ "${GITHUB_REF_NAME}" == draft* ]]; then
+  #           echo "BUILD_TYPE=draft" >> $GITHUB_ENV
+  #         elif [[ "${GITHUB_REF_NAME}" == release* ]]; then
+  #           echo "BUILD_TYPE=release" >> $GITHUB_ENV
+  #         else
+  #           echo "BUILD_TYPE=default" >> $GITHUB_ENV
+  #         fi
 
-      - name: Deploy via SSH
-        uses: appleboy/ssh-action@v1.0.3
-        with:
-          host: ${{ secrets.SSH_HOST }}
-          username: ${{ secrets.SSH_USERNAME }}
-          key: ${{ secrets.SSH_PRIVATE_KEY }}
-          script: |
-            REPO_DIR="~/ONDC-automation-framework/api-service/automation-api-service-${{ github.ref_name }}"
-            mkdir -p $REPO_DIR
+  #     - name: Deploy via SSH
+  #       uses: appleboy/ssh-action@v1.0.3
+  #       with:
+  #         host: ${{ secrets.SSH_HOST }}
+  #         username: ${{ secrets.SSH_USERNAME }}
+  #         key: ${{ secrets.SSH_PRIVATE_KEY }}
+  #         script: |
+  #           REPO_DIR="~/ONDC-automation-framework/api-service/automation-api-service-${{ github.ref_name }}"
+  #           mkdir -p $REPO_DIR
 
-            echo "Writing .env file..."
-            cat > $REPO_DIR/.env <<EOF
-            REDIS_USERNAME=${{ vars.REDIS_USERNAME }}
-            REDIS_HOST=${{ vars.REDIS_HOST }}
-            REDIS_PASSWORD=${{ secrets.REDIS_PASSWORD }}
-            REDIS_PORT=${{ vars.REDIS_PORT }}
-            PORT=${{ vars. API_SERVICE_PORT }}
-            API_SERVICE_URL=${{  vars.API_SERVICE_URL }}
-            DOMAIN=${{ vars.DOMAIN }}
-            CONFIG_SERVICE_URL=${{ vars.CONFIG_SERVICE_URL }}
-            API_SERVICE_KEY=${{ secrets.API_SERVICE_KEY_DEV }}
-            FORM_SERVICE=${{ vars.FORM_SERVICE }}
-            NODE_ENV=${{ vars.NODE_ENV }}
-            LOKI_HOST=${{ vars.LOKI_HOST }}
-            EOF
+  #           echo "Writing .env file..."
+  #           cat > $REPO_DIR/.env <<EOF
+  #           REDIS_USERNAME=${{ vars.REDIS_USERNAME }}
+  #           REDIS_HOST=${{ vars.REDIS_HOST }}
+  #           REDIS_PASSWORD=${{ secrets.REDIS_PASSWORD }}
+  #           REDIS_PORT=${{ vars.REDIS_PORT }}
+  #           PORT=${{ vars. API_SERVICE_PORT }}
+  #           API_SERVICE_URL=${{  vars.API_SERVICE_URL }}
+  #           DOMAIN=${{ vars.DOMAIN }}
+  #           CONFIG_SERVICE_URL=${{ vars.CONFIG_SERVICE_URL }}
+  #           API_SERVICE_KEY=${{ secrets.API_SERVICE_KEY_DEV }}
+  #           FORM_SERVICE=${{ vars.FORM_SERVICE }}
+  #           NODE_ENV=${{ vars.NODE_ENV }}
+  #           LOKI_HOST=${{ vars.LOKI_HOST }}
+  #           EOF
 
-            IMAGE_NAME=ghcr.io/ondc-official/automation-api-service-${{vars.CONTAINER_NAME}}
+  #           IMAGE_NAME=ghcr.io/ondc-official/automation-api-service-${{vars.CONTAINER_NAME}}
 
-            echo "Pulling latest image..."
-            docker pull $IMAGE_NAME:stable || docker pull $IMAGE_NAME:stable
+  #           echo "Pulling latest image..."
+  #           docker pull $IMAGE_NAME:stable || docker pull $IMAGE_NAME:stable
 
-            echo "Restarting container..."
-            docker stop automation-api-service-${{ vars.CONTAINER_NAME }} || true
-            docker rm automation-api-service-${{ vars.CONTAINER_NAME }} || true
+  #           echo "Restarting container..."
+  #           docker stop automation-api-service-${{ vars.CONTAINER_NAME }} || true
+  #           docker rm automation-api-service-${{ vars.CONTAINER_NAME }} || true
 
-            docker run -d --name automation-api-service-${{ vars.CONTAINER_NAME }} \
-              --env-file $REPO_DIR/.env \
-              -p ${{ vars. API_SERVICE_PORT }}:${{ vars. API_SERVICE_PORT }} \
-              $IMAGE_NAME:stable
+  #           docker run -d --name automation-api-service-${{ vars.CONTAINER_NAME }} \
+  #             --env-file $REPO_DIR/.env \
+  #             -p ${{ vars. API_SERVICE_PORT }}:${{ vars. API_SERVICE_PORT }} \
+  #             $IMAGE_NAME:stable
