merged changes

diff --git a/.github/workflows/merged-workflow.yml b/.github/workflows/merged-workflow.yml
--- a/.github/workflows/merged-workflow.yml
+++ b/.github/workflows/merged-workflow.yml
@@ -30,3 +30,297 @@ jobs:
           fi
           echo "Detected BUILD_TYPE=$BUILD_TYPE"
           echo "Detected BUILD_TYPE=${{ steps.set_build_type.outputs.build_type }}"
+
+
+      - name: Prepare build repo for api service
+        run: |
+         echo "building api service"
+         echo "Cloning generator repo..."
+          # ls -R $GITHUB_WORKSPACE
+          git clone --single-branch --branch main https://github.com/ONDC-Official/automation-api-service-generator.git automation-api-service-generator
+          # git clone --single-branch --branch main https://github.com/ONDC-Official/automation-api-service-generator.git automation-api-service-generator
+          # ls -R automation-api-service-generator
+          echo "Initializing submodules..."
+          cd automation-api-service-generator
+          GENERATOR_SHA=$(git rev-parse HEAD)
+          TAG="$GITHUB_SHA-$GENERATOR_SHA"
+          echo "TAG=$TAG" >> $GITHUB_ENV
+          echo "TAG in this step: $TAG"
+          GENERATOR_SHA=$(git rev-parse HEAD)
+          git submodule update --init --recursive
+          echo "Copying api-config from current repo..."
+          cp -rf $GITHUB_WORKSPACE/api-service/src/config/* ./src/config/
+          # ls -R automation-api-service-generator/src
+          echo "Build repo ready at $(pwd)"
+
+      - name: Log in to GHCR
+        uses: docker/login-action@v3
+        with:
+          registry: ghcr.io
+          username: ${{ github.actor }}
+          password: ${{ secrets.GIT_PAT }}
+
+
+      - name: Build Docker image
+        run: |
+          cd automation-api-service-generator
+          echo "TAG in this step: $TAG"
+          IMAGE_NAME=ghcr.io/ondc-official/automation-api-service-${{vars.CONTAINER_NAME}}
+          docker build -t $IMAGE_NAME:$TAG .
+          echo "$TAG"
+        env:
+          DOCKER_BUILDKIT: 1
+
+      - name: Run container locally
+        run: |
+          IMAGE_NAME=ghcr.io/ondc-official/automation-api-service-${{vars.CONTAINER_NAME}}
+
+
+          if [[ "$BUILD_TYPE" == "draft" ]]; then
+  
+          cat > ./.env <<EOF
+          NODE_ENV=${{ vars.NODE_ENV }}
+          SIGN_PRIVATE_KEY=${{ secrets.SIGN_PRIVATE_KEY }}
+          PORT=${{ vars.API_SERVICE_PORT }}
+          SIGN_PUBLIC_KEY=${{ vars.SIGN_PUBLIC_KEY }}
+          SUBSCRIBER_ID=${{ vars.SUBSCRIBER_ID }}
+          UKID=${{ vars.UKID }}
+          ONDC_ENV=${{ vars.ONDC_ENV }}
+          REDIS_USERNAME=${{ vars.REDIS_USERNAME }}
+          REDIS_HOST=${{ vars.REDIS_HOST }}
+          REDIS_PASSWORD=${{ secrets.REDIS_PASSWORD }}
+          REDIS_PORT=${{ vars.REDIS_PORT }}
+          WORKBENCH_SUBSCRIBER_ID=${{ vars.WORKBENCH_SUBSCRIBER_ID }}
+          IN_HOUSE_REGISTRY=${{ vars.IN_HOUSE_REGISTRY }}
+          MOCK_SERVER_URL=${{ vars.MOCK_SERVER_URL }}
+          DATA_BASE_URL=${{ vars.DATA_BASE_URL }}
+          API_SERVICE_URL=${{ vars.API_SERVICE_URL }}
+          CONFIG_SERVICE_URL=${{ vars.CONFIG_SERVICE_URL }}
+          CONTAINER_NAME=${{ vars.CONTAINER_NAME }}
+          DOMAIN=${{ vars.DOMAIN }}
+          VERSION=${{ vars.VERSION }}
+          SERVICE_NAME=automation-api-service-${{ vars.CONTAINER_NAME }}
+          TRACE_URL=${{ vars.TRACE_URL }}
+          API_SERVICE_KEY=${{ secrets.API_SERVICE_KEY_DEV }}
+          LOKI_HOST=${{ vars.LOKI_HOST }}
+          HOSTED_ENV=${{ vars.HOSTED_ENV_DEV }}
+          NO_URL=${{ vars.NO_URL }}
+          NO_TOKEN=${{ secrets.NO_TOKEN }}
+          EOF
+          
+          elif [[ "$BUILD_TYPE" == "release" ]]; then
+          cat > ./.env <<EOF
+          NODE_ENV=${{ vars.NODE_ENV }}
+          SIGN_PRIVATE_KEY=${{ secrets.SIGN_PRIVATE_KEY }}
+          PORT=${{ vars.API_SERVICE_PORT }}
+          SIGN_PUBLIC_KEY=${{ vars.SIGN_PUBLIC_KEY }}
+          SUBSCRIBER_ID=${{ vars.SUBSCRIBER_ID_STAGING }}
+          UKID=${{ vars.UKID_STAGING }}
+          ONDC_ENV=${{ vars.ONDC_ENV }}
+          REDIS_USERNAME=${{ vars.REDIS_USERNAME }}
+          REDIS_HOST=${{ vars.REDIS_HOST }}
+          REDIS_PASSWORD=${{ secrets.REDIS_PASSWORD }}
+          REDIS_PORT=${{ vars.REDIS_PORT_STAGING }}
+          MOCK_SERVER_URL=${{ vars.MOCK_SERVER_URL_STAGING }}
+          DATA_BASE_URL=${{ vars.DATA_BASE_URL_STAGING }}
+          API_SERVICE_URL=${{ vars.API_SERVICE_URL_STAGING }}
+          CONTAINER_NAME=${{ vars.CONTAINER_NAME }}
+          CONFIG_SERVICE_URL=${{ vars.CONFIG_SERVICE_URL_STAGING }}
+          DOMAIN=${{ vars.DOMAIN }}
+          VERSION=${{ vars.VERSION }}
+          SERVICE_NAME=automation-api-service-${{ vars.CONTAINER_NAME }}
+          TRACE_URL=${{ vars.TRACE_URL_STAGING }}
+          API_SERVICE_KEY=${{ secrets.API_SERVICE_KEY_STAGING }}
+          LOKI_HOST=${{ vars.LOKI_HOST }}
+          WORKBENCH_SUBSCRIBER_ID=${{ vars.WORKBENCH_SUBSCRIBER_ID }}
+          IN_HOUSE_REGISTRY=${{ vars.IN_HOUSE_REGISTRY_STAGING }}
+          HOSTED_ENV=${{ vars.HOSTED_ENV_STAGING }}
+          NO_URL=${{ vars.NO_URL }}
+          NO_TOKEN=${{ secrets.NO_TOKEN }}
+
+
+          EOF
+          fi
+            
+          # docker run -d --rm --name api-test \
+          #   -p ${{ vars. API_SERVICE_PORT }}:${{ vars. API_SERVICE_PORT }} \
+          #   --env-file ./.env \
+          #   $IMAGE_NAME:$TAG
+          # sleep 5
+
+          docker run -d --name api-test \
+            -p ${{ vars. API_SERVICE_PORT }}:${{ vars. API_SERVICE_PORT }} \
+            --env-file .env \
+            $IMAGE_NAME:$TAG
+      
+          echo "⏳ Waiting for service..."
+          sleep 5
+      
+          echo "📋 Container status:"
+          docker ps -a
+      
+          echo "📜 Logs:"
+          docker logs api-test || true
+      
+          # echo "🔍 Health check:"
+          # curl -v http://localhost:${{ vars. API_SERVICE_PORT }}/health || true
+
+      - name: Healthcheck
+        run: |
+          HEALTHCHECK_URL="http://localhost:${{ vars.API_SERVICE_PORT}}/api-service/${{ vars.DOMAIN }}/${{vars.VERSION}}/health"
+          echo "Checking $HEALTHCHECK_URL ..."
+          for i in {1..10}; do
+            if curl -sSf "$HEALTHCHECK_URL" > /dev/null; then
+              echo "✅ Container is healthy"
+              exit 0
+            fi
+            echo "Waiting... ($i)"
+            sleep 2
+          done
+          echo "❌ Healthcheck failed!"
+          docker logs api-test
+          exit 1
+
+      - name: Stop test container
+        if: always()
+        run: docker stop api-test || true
+
+      - name: Tag & Push Images
+        run: |
+          echo TAG in next step: $TAG
+          IMAGE_NAME=ghcr.io/ondc-official/automation-api-service-${{vars.CONTAINER_NAME}}
+          docker tag $IMAGE_NAME:$TAG $IMAGE_NAME:latest
+          docker tag $IMAGE_NAME:$TAG $IMAGE_NAME:stable
+          docker push $IMAGE_NAME:$TAG
+          docker push $IMAGE_NAME:latest
+          docker push $IMAGE_NAME:stable
+
+
+  # build mock service 
+      - name: Prepare build repo
+        run: |
+          cd $HOME
+          echo "Cloning generator repo..."
+          # ls -R $GITHUB_WORKSPACE
+          git clone --single-branch --branch main https://github.com/ONDC-Official/automation-mock-service-generator.git automation-mock-service-generator
+          # ls -R automation-mock-service-generator
+          echo "Initializing submodules..."
+          cd automation-mock-service-generator
+          GENERATOR_SHA=$(git rev-parse HEAD)
+          TAG="$GITHUB_SHA-$GENERATOR_SHA"
+          echo "TAG=$TAG" >> $GITHUB_ENV
+          echo "TAG in this step: $TAG"
+          GENERATOR_SHA=$(git rev-parse HEAD)
+          git submodule update --init --recursive
+          echo "Copying mock-config from current repo..."
+          cp -r $GITHUB_WORKSPACE/mock-service/src/config/mock-config ./src/config/
+
+          echo "Build repo ready at $(pwd)"
+
+      - name: Log in to GHCR
+        uses: docker/login-action@v3
+        with:
+          registry: ghcr.io
+          username: ${{ github.actor }}
+          password: ${{ secrets.GIT_PAT }}
+
+
+      - name: Build Docker image
+        run: |
+          cd automation-mock-service-generator
+          echo "TAG in this step: $TAG"
+          IMAGE_NAME=ghcr.io/ondc-official/automation-mock-service-${{vars.CONTAINER_NAME}}
+          docker build -t $IMAGE_NAME:$TAG .
+          echo "$TAG"
+        env:
+          DOCKER_BUILDKIT: 1
+
+      - name: Run container locally
+        run: |
+          IMAGE_NAME=ghcr.io/ondc-official/automation-mock-service-${{vars.CONTAINER_NAME}}
+          if [[ "$BUILD_TYPE" == "draft" ]]; then
+          cat > .env <<EOF
+          REDIS_USERNAME=${{ vars.REDIS_USERNAME }}
+          REDIS_HOST=${{ vars.REDIS_HOST }}
+          REDIS_PASSWORD=${{ secrets.REDIS_PASSWORD }}
+          REDIS_PORT=${{ vars.REDIS_PORT }}
+          PORT=${{ vars.MOCK_SERVICE_PORT }}
+          API_SERVICE_URL=${{ vars.API_SERVICE_URL }}
+          DOMAIN=${{ vars.DOMAIN }}
+          CONFIG_SERVICE_URL=${{ vars.CONFIG_SERVICE_URL }}
+          API_SERVICE_KEY=${{ secrets.API_SERVICE_KEY_DEV }}
+          FORM_SERVICE=${{ vars.FORM_SERVICE }}
+          NODE_ENV=${{ vars.NODE_ENV }}
+          LOKI_HOST=${{ vars.LOKI_HOST }}
+          EOF
+
+          elif [[ "$BUILD_TYPE" == "release" ]]; then
+          cat > .env <<EOF
+          REDIS_USERNAME=${{ vars.REDIS_USERNAME }}
+          REDIS_HOST=${{ vars.REDIS_HOST }}
+          REDIS_PASSWORD=${{ secrets.REDIS_PASSWORD }}
+          REDIS_PORT=${{ vars.REDIS_PORT_STAGING }}
+          PORT=${{ vars.MOCK_SERVICE_PORT }}
+          API_SERVICE_URL=${{ vars.API_SERVICE_URL_STAGING }}
+          DOMAIN=${{ vars.DOMAIN }}
+          CONFIG_SERVICE_URL=${{ vars.CONFIG_SERVICE_URL_STAGING }}
+          API_SERVICE_KEY=${{ secrets.API_SERVICE_KEY_STAGING }}
+          FORM_SERVICE=${{ vars.FORM_SERVICE }}
+          NODE_ENV=${{ vars.NODE_ENV }}
+          LOKI_HOST=${{ vars.LOKI_HOST }}
+          EOF
+          fi
+
+            
+          # docker run -d --rm --name mock-test \
+          #   -p ${{ vars.MOCK_SERVICE_PORT }}:${{ vars.MOCK_SERVICE_PORT }} \
+          #   --env-file ./.env \
+          #   $IMAGE_NAME:$TAG
+          # sleep 5
+
+          docker run -d --name mock-test \
+            -p ${{ vars.MOCK_SERVICE_PORT }}:${{ vars.MOCK_SERVICE_PORT }} \
+            --env-file .env \
+            $IMAGE_NAME:$TAG
+      
+          # echo "⏳ Waiting for service..."
+          # sleep 5
+      
+          # echo "📋 Container status:"
+          # docker ps -a
+      
+          # echo "📜 Logs:"
+          # docker logs mock-test || true
+      
+          # echo "🔍 Health check:"
+          # curl -v http://localhost:${{ vars.MOCK_SERVICE_PORT }}/health || true
+
+      - name: Healthcheck
+        run: |
+          HEALTHCHECK_URL="http://localhost:${{ vars.MOCK_SERVICE_PORT }}/mock/${{ vars.DOMAIN }}/health"
+          echo "Checking $HEALTHCHECK_URL ..."
+          for i in {1..10}; do
+            if curl -sSf "$HEALTHCHECK_URL" > /dev/null; then
+              echo "✅ Container is healthy"
+              exit 0
+            fi
+            echo "Waiting... ($i)"
+            sleep 2
+          done
+          echo "❌ Healthcheck failed!"
+          docker logs mock-test
+          exit 1
+
+      - name: Stop test container
+        if: always()
+        run: docker stop mock-test || true
+
+      - name: Tag & Push Images
+        run: |
+          echo TAG in next step: $TAG
+          IMAGE_NAME=ghcr.io/ondc-official/automation-mock-service-${{vars.CONTAINER_NAME}}
+          docker tag $IMAGE_NAME:$TAG $IMAGE_NAME:latest
+          docker tag $IMAGE_NAME:$TAG $IMAGE_NAME:stable
+          docker push $IMAGE_NAME:$TAG
+          docker push $IMAGE_NAME:latest
+          docker push $IMAGE_NAME:stable
