Update new-workflow.yml

diff --git a/.github/workflows/new-workflow.yml b/.github/workflows/new-workflow.yml
--- a/.github/workflows/new-workflow.yml
+++ b/.github/workflows/new-workflow.yml
@@ -59,65 +59,66 @@ jobs:
       - name: Build Docker image
         run: |
           cd automation-mock-service-generator
+          echo "TAG in this step: $TAG"
           IMAGE_NAME=ghcr.io/ondc-official/automation-mock-service-${BUILD_TYPE}-${{vars.CONTAINER_NAME}}
-          docker build -t $IMAGE_NAME:${{ github.sha }}-${GENERATOR_SHA} .
+          # docker build -t $IMAGE_NAME:${{ github.sha }}-${GENERATOR_SHA} .
           echo "${{ github.sha }}-${GENERATOR_SHA}"
         env:
           DOCKER_BUILDKIT: 1
 
-      - name: Run container locally
-        run: |
-          IMAGE_NAME=ghcr.io/ondc-official/automation-mock-service-${BUILD_TYPE}-${{vars.CONTAINER_NAME}}
-          cat > ./.env <<EOF
-              REDIS_USERNAME=${{ vars.REDIS_USERNAME }}
-              REDIS_HOST=${{ vars.REDIS_HOST }}
-              REDIS_PASSWORD=${{ secrets.REDIS_PASSWORD }}
-              REDIS_PORT=${{ vars.REDIS_PORT }}
-              PORT=${{ vars.PORT }}
-              API_SERVICE_URL=${{  secrets.API_SERVICE_KEY_DEV }}
-              DOMAIN=${{ vars.DOMAIN }}
-              CONFIG_SERVICE_URL=${{ vars.CONFIG_SERVICE_URL }}
-              API_SERVICE_KEY=${{ secrets.API_SERVICE_KEY }}
-              FORM_SERVICE=${{ vars.FORM_SERVICE }}
-              NODE_ENV=${{ vars.NODE_ENV }}
-              LOKI_HOST=${{ vars.LOKI_HOST }}
-            EOF
+      # - name: Run container locally
+      #   run: |
+      #     IMAGE_NAME=ghcr.io/ondc-official/automation-mock-service-${BUILD_TYPE}-${{vars.CONTAINER_NAME}}
+      #     cat > ./.env <<EOF
+      #         REDIS_USERNAME=${{ vars.REDIS_USERNAME }}
+      #         REDIS_HOST=${{ vars.REDIS_HOST }}
+      #         REDIS_PASSWORD=${{ secrets.REDIS_PASSWORD }}
+      #         REDIS_PORT=${{ vars.REDIS_PORT }}
+      #         PORT=${{ vars.PORT }}
+      #         API_SERVICE_URL=${{  secrets.API_SERVICE_KEY_DEV }}
+      #         DOMAIN=${{ vars.DOMAIN }}
+      #         CONFIG_SERVICE_URL=${{ vars.CONFIG_SERVICE_URL }}
+      #         API_SERVICE_KEY=${{ secrets.API_SERVICE_KEY }}
+      #         FORM_SERVICE=${{ vars.FORM_SERVICE }}
+      #         NODE_ENV=${{ vars.NODE_ENV }}
+      #         LOKI_HOST=${{ vars.LOKI_HOST }}
+      #       EOF
             
-          docker run -d --rm --name mock-test \
-            -p ${{ vars.PORT }}:${{ vars.PORT }} \
-            --env-file ./.env \
-            $IMAGE_NAME:${{ github.sha }}-${GENERATOR_SHA}
-          sleep 15
+      #     docker run -d --rm --name mock-test \
+      #       -p ${{ vars.PORT }}:${{ vars.PORT }} \
+      #       --env-file ./.env \
+      #       $IMAGE_NAME:${{ github.sha }}-${GENERATOR_SHA}
+      #     sleep 15
 
-      - name: Healthcheck
-        run: |
-          HEALTHCHECK_URL="http://localhost:${{ vars.PORT }}/mock/${{ vars.DOMAIN }}/health"
-          echo "Checking $HEALTHCHECK_URL ..."
-          for i in {1..10}; do
-            if curl -sSf "$HEALTHCHECK_URL" > /dev/null; then
-              echo "✅ Container is healthy"
-              exit 0
-            fi
-            echo "Waiting... ($i)"
-            sleep 2
-          done
-          echo "❌ Healthcheck failed!"
-          docker logs mock-test
-          exit 1
+      # - name: Healthcheck
+      #   run: |
+      #     HEALTHCHECK_URL="http://localhost:${{ vars.PORT }}/mock/${{ vars.DOMAIN }}/health"
+      #     echo "Checking $HEALTHCHECK_URL ..."
+      #     for i in {1..10}; do
+      #       if curl -sSf "$HEALTHCHECK_URL" > /dev/null; then
+      #         echo "✅ Container is healthy"
+      #         exit 0
+      #       fi
+      #       echo "Waiting... ($i)"
+      #       sleep 2
+      #     done
+      #     echo "❌ Healthcheck failed!"
+      #     docker logs mock-test
+      #     exit 1
 
-      - name: Stop test container
-        if: always()
-        run: docker stop mock-test || true
+      # - name: Stop test container
+      #   if: always()
+      #   run: docker stop mock-test || true
 
-      - name: Tag & Push Images
-        run: |
-          echo TAG in next step: $TAG
-          # IMAGE_NAME=ghcr.io/ondc-official/automation-mock-service-${BUILD_TYPE}-${{vars.CONTAINER_NAME}}
-          # docker tag $IMAGE_NAME:${{ github.sha }}-${GENERATOR_SHA} $IMAGE_NAME:latest
-          # docker tag $IMAGE_NAME:${{ github.sha }}-${GENERATOR_SHA} $IMAGE_NAME:stable
-          # docker push $IMAGE_NAME:${{ github.sha }}-${GENERATOR_SHA}
-          # docker push $IMAGE_NAME:latest
-          # docker push $IMAGE_NAME:stable
+      # - name: Tag & Push Images
+      #   run: |
+      #     echo TAG in next step: $TAG
+      #     # IMAGE_NAME=ghcr.io/ondc-official/automation-mock-service-${BUILD_TYPE}-${{vars.CONTAINER_NAME}}
+      #     # docker tag $IMAGE_NAME:${{ github.sha }}-${GENERATOR_SHA} $IMAGE_NAME:latest
+      #     # docker tag $IMAGE_NAME:${{ github.sha }}-${GENERATOR_SHA} $IMAGE_NAME:stable
+      #     # docker push $IMAGE_NAME:${{ github.sha }}-${GENERATOR_SHA}
+      #     # docker push $IMAGE_NAME:latest
+      #     # docker push $IMAGE_NAME:stable
 
   # deploy:
   #   needs: build-and-verify
