Update new-workflow.yml

diff --git a/.github/workflows/new-workflow.yml b/.github/workflows/new-workflow.yml
--- a/.github/workflows/new-workflow.yml
+++ b/.github/workflows/new-workflow.yml
@@ -88,23 +88,23 @@ jobs:
             -p ${{ vars.PORT }}:${{ vars.PORT }} \
             --env-file ./.env \
             $IMAGE_NAME:$TAG
-          sleep 15
+          sleep 5
 
-      - name: Healthcheck
-        run: |
-          HEALTHCHECK_URL="http://localhost:${{ vars.PORT }}/mock/${{ vars.DOMAIN }}/health"
-          echo "Checking $HEALTHCHECK_URL ..."
-          for i in {1..10}; do
-            if curl -sSf "$HEALTHCHECK_URL" > /dev/null; then
-              echo "✅ Container is healthy"
-              exit 0
-            fi
-            echo "Waiting... ($i)"
-            sleep 2
-          done
-          echo "❌ Healthcheck failed!"
-          docker logs mock-test
-          exit 1
+      # - name: Healthcheck
+      #   run: |
+      #     HEALTHCHECK_URL="http://localhost:${{ vars.PORT }}/mock/${{ vars.DOMAIN }}/health"
+      #     echo "Checking $HEALTHCHECK_URL ..."
+      #     for i in {1..10}; do
+      #       if curl -sSf "$HEALTHCHECK_URL" > /dev/null; then
+      #         echo "✅ Container is healthy"
+      #         exit 0
+      #       fi
+      #       echo "Waiting... ($i)"
+      #       sleep 2
+      #     done
+      #     echo "❌ Healthcheck failed!"
+      #     docker logs mock-test
+      #     exit 1
 
       - name: Stop test container
         if: always()
