Update new-workflow.yml

diff --git a/.github/workflows/new-workflow.yml b/.github/workflows/new-workflow.yml
--- a/.github/workflows/new-workflow.yml
+++ b/.github/workflows/new-workflow.yml
@@ -60,49 +60,49 @@ jobs:
         env:
           DOCKER_BUILDKIT: 1
 
-      - name: Run container locally
-        run: |
-          IMAGE_NAME=ghcr.io/ondc-official/automation-mock-service-${BUILD_TYPE}-${{vars.CONTAINER_NAME}}
-          cat > ./.env <<EOF
-              REDIS_USERNAME=${{ secrets.REDIS_USERNAME }}
-              REDIS_HOST=${{ secrets.REDIS_HOST }}
-              REDIS_PASSWORD=${{ secrets.REDIS_PASSWORD }}
-              REDIS_PORT=${{ secrets.REDIS_PORT }}
-              PORT=${{ vars.PORT }}
-              API_SERVICE_URL=${{ vars.API_SERVICE_URL }}
-              DOMAIN=${{ vars.DOMAIN }}
-              CONFIG_SERVICE_URL=${{ vars.CONFIG_SERVICE_URL }}
-              API_SERVICE_KEY=${{ secrets.API_SERVICE_KEY }}
-              FORM_SERVICE=${{ vars.FORM_SERVICE }}
-              NODE_ENV=${{ vars.NODE_ENV }}
-              LOKI_HOST=${{ vars.LOKI_HOST }}
-            EOF
+      # - name: Run container locally
+      #   run: |
+      #     IMAGE_NAME=ghcr.io/ondc-official/automation-mock-service-${BUILD_TYPE}-${{vars.CONTAINER_NAME}}
+      #     cat > ./.env <<EOF
+      #         REDIS_USERNAME=${{ secrets.REDIS_USERNAME }}
+      #         REDIS_HOST=${{ secrets.REDIS_HOST }}
+      #         REDIS_PASSWORD=${{ secrets.REDIS_PASSWORD }}
+      #         REDIS_PORT=${{ secrets.REDIS_PORT }}
+      #         PORT=${{ vars.PORT }}
+      #         API_SERVICE_URL=${{ vars.API_SERVICE_URL }}
+      #         DOMAIN=${{ vars.DOMAIN }}
+      #         CONFIG_SERVICE_URL=${{ vars.CONFIG_SERVICE_URL }}
+      #         API_SERVICE_KEY=${{ secrets.API_SERVICE_KEY }}
+      #         FORM_SERVICE=${{ vars.FORM_SERVICE }}
+      #         NODE_ENV=${{ vars.NODE_ENV }}
+      #         LOKI_HOST=${{ vars.LOKI_HOST }}
+      #       EOF
             
-          docker run -d --rm --name mock-test \
-            -p ${{ vars.PORT }}:${{ vars.PORT }} \
-            --env-file ./.env \
-            $IMAGE_NAME:${{ github.sha }}
-          sleep 5
+      #     docker run -d --rm --name mock-test \
+      #       -p ${{ vars.PORT }}:${{ vars.PORT }} \
+      #       --env-file ./.env \
+      #       $IMAGE_NAME:${{ github.sha }}
+      #     sleep 5
 
-      - name: Healthcheck
-        run: |
-          HEALTHCHECK_URL="http://localhost:${{ vars.PORT }}/mock/${{ vars.DOMAIN }}/health"
-          echo "Checking $HEALTHCHECK_URL ..."
-          for i in {1..10}; do
-            if curl -sSf "$HEALTHCHECK_URL" > /dev/null; then
-              echo "✅ Container is healthy"
-              exit 0
-            fi
-            echo "Waiting... ($i)"
-            sleep 2
-          done
-          echo "❌ Healthcheck failed!"
-          docker logs mock-test
-          exit 1
+      # - name: Healthcheck
+      #   run: |
+      #     HEALTHCHECK_URL="http://localhost:${{ vars.PORT }}/mock/${{ vars.DOMAIN }}/health"
+      #     echo "Checking $HEALTHCHECK_URL ..."
+      #     for i in {1..10}; do
+      #       if curl -sSf "$HEALTHCHECK_URL" > /dev/null; then
+      #         echo "✅ Container is healthy"
+      #         exit 0
+      #       fi
+      #       echo "Waiting... ($i)"
+      #       sleep 2
+      #     done
+      #     echo "❌ Healthcheck failed!"
+      #     docker logs mock-test
+      #     exit 1
 
-      - name: Stop test container
-        if: always()
-        run: docker stop mock-test || true
+      # - name: Stop test container
+      #   if: always()
+      #   run: docker stop mock-test || true
 
       - name: Tag & Push Images
         run: |
@@ -113,64 +113,57 @@ jobs:
           docker push $IMAGE_NAME:latest
           docker push $IMAGE_NAME:stable
 
-  deploy:
-    needs: build-and-verify
-    runs-on: ubuntu-latest
-    environment: |
-      ${{
-        (startsWith(github.ref_name, 'release') && format('release-{0}', github.ref_name)) ||
-        (startsWith(github.ref_name, 'draft') && format('draft-{0}', github.ref_name)) ||
-        (startsWith(github.ref_name, 'release') && 'release') ||
-        (startsWith(github.ref_name, 'draft') && 'draft') ||
-        'default'
-      }}
-    steps:
-      - name: Detect build type
-        run: |
-          if [[ "${GITHUB_REF_NAME}" == draft* ]]; then
-            echo "BUILD_TYPE=draft" >> $GITHUB_ENV
-          elif [[ "${GITHUB_REF_NAME}" == release* ]]; then
-            echo "BUILD_TYPE=release" >> $GITHUB_ENV
-          else
-            echo "BUILD_TYPE=default" >> $GITHUB_ENV
-          fi
+  # deploy:
+  #   needs: build-and-verify
+  #   runs-on: ubuntu-latest
+  #   environment: ${{ github.ref_name }}  # environment exactly matches branch name
+  #   steps:
+  #     - name: Detect build type
+  #       run: |
+  #         if [[ "${GITHUB_REF_NAME}" == draft* ]]; then
+  #           echo "BUILD_TYPE=draft" >> $GITHUB_ENV
+  #         elif [[ "${GITHUB_REF_NAME}" == release* ]]; then
+  #           echo "BUILD_TYPE=release" >> $GITHUB_ENV
+  #         else
+  #           echo "BUILD_TYPE=default" >> $GITHUB_ENV
+  #         fi
 
-      - name: Deploy via SSH
-        uses: appleboy/ssh-action@v1.0.3
-        with:
-          host: ${{ secrets.SSH_HOST }}
-          username: ${{ secrets.SSH_USERNAME }}
-          key: ${{ secrets.SSH_PRIVATE_KEY }}
-          script: |
-            REPO_DIR="/opt/automation-mock-service-${BUILD_TYPE}-${{ vars.DOMAIN }}-${{ vars.VERSION }}"
-            mkdir -p $REPO_DIR
+  #     - name: Deploy via SSH
+  #       uses: appleboy/ssh-action@v1.0.3
+  #       with:
+  #         host: ${{ secrets.SSH_HOST }}
+  #         username: ${{ secrets.SSH_USERNAME }}
+  #         key: ${{ secrets.SSH_PRIVATE_KEY }}
+  #         script: |
+  #           REPO_DIR="/opt/automation-mock-service-${BUILD_TYPE}-${{ vars.DOMAIN }}-${{ vars.VERSION }}"
+  #           mkdir -p $REPO_DIR
 
-            echo "Writing .env file..."
-            cat > $REPO_DIR/.env <<EOF
-            REDIS_USERNAME=${{ secrets.REDIS_USERNAME }}
-            REDIS_HOST=${{ secrets.REDIS_HOST }}
-            REDIS_PASSWORD=${{ secrets.REDIS_PASSWORD }}
-            REDIS_PORT=${{ secrets.REDIS_PORT }}
-            PORT=${{ vars.PORT }}
-            API_SERVICE_URL=${{ vars.API_SERVICE_URL }}
-            DOMAIN=${{ vars.DOMAIN }}
-            CONFIG_SERVICE_URL=${{ vars.CONFIG_SERVICE_URL }}
-            API_SERVICE_KEY=${{ secrets.API_SERVICE_KEY }}
-            FORM_SERVICE=${{ vars.FORM_SERVICE }}
-            NODE_ENV=${{ vars.NODE_ENV }}
-            LOKI_HOST=${{ vars.LOKI_HOST }}
-            EOF
+  #           echo "Writing .env file..."
+  #           cat > $REPO_DIR/.env <<EOF
+  #           REDIS_USERNAME=${{ secrets.REDIS_USERNAME }}
+  #           REDIS_HOST=${{ secrets.REDIS_HOST }}
+  #           REDIS_PASSWORD=${{ secrets.REDIS_PASSWORD }}
+  #           REDIS_PORT=${{ secrets.REDIS_PORT }}
+  #           PORT=${{ vars.PORT }}
+  #           API_SERVICE_URL=${{ vars.API_SERVICE_URL }}
+  #           DOMAIN=${{ vars.DOMAIN }}
+  #           CONFIG_SERVICE_URL=${{ vars.CONFIG_SERVICE_URL }}
+  #           API_SERVICE_KEY=${{ secrets.API_SERVICE_KEY }}
+  #           FORM_SERVICE=${{ vars.FORM_SERVICE }}
+  #           NODE_ENV=${{ vars.NODE_ENV }}
+  #           LOKI_HOST=${{ vars.LOKI_HOST }}
+  #           EOF
 
-            IMAGE_NAME=ghcr.io/ondc-official/automation-mock-service-${BUILD_TYPE}-${{vars.CONTAINER_NAME}}
+  #           IMAGE_NAME=ghcr.io/ondc-official/automation-mock-service-${BUILD_TYPE}-${{vars.CONTAINER_NAME}}
 
-            echo "Pulling latest image..."
-            docker pull $IMAGE_NAME:stable || docker pull $IMAGE_NAME:${{ github.sha }}
+  #           echo "Pulling latest image..."
+  #           docker pull $IMAGE_NAME:stable || docker pull $IMAGE_NAME:${{ github.sha }}
 
-            echo "Restarting container..."
-            docker stop automation-mock-service-${BUILD_TYPE}-${{ vars.DOMAIN }}-${{ vars.VERSION }} || true
-            docker rm automation-mock-service-${BUILD_TYPE}-${{ vars.DOMAIN }}-${{ vars.VERSION }} || true
+  #           echo "Restarting container..."
+  #           docker stop automation-mock-service-${BUILD_TYPE}-${{ vars.DOMAIN }}-${{ vars.VERSION }} || true
+  #           docker rm automation-mock-service-${BUILD_TYPE}-${{ vars.DOMAIN }}-${{ vars.VERSION }} || true
 
-            docker run -d --name automation-mock-service-${BUILD_TYPE}-${{ vars.DOMAIN }}-${{ vars.VERSION }} \
-              --env-file $REPO_DIR/.env \
-              -p ${{ vars.PORT }}:${{ vars.PORT }} \
+  #           docker run -d --name automation-mock-service-${BUILD_TYPE}-${{ vars.DOMAIN }}-${{ vars.VERSION }} \
+  #             --env-file $REPO_DIR/.env \
+  #             -p ${{ vars.PORT }}:${{ vars.PORT }} \
               $IMAGE_NAME:stable
